# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = 'Publications'
  url = '#publication'
  weight = 10

[[main]]
  name = 'Web applications'
  url = '#applications-and-dashboards'
  weight = 20
  
[[main]]
  name = 'Workshops & presentations'
  url = '#workshops'
  weight = 30

[[main]]
  name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; CV &nbsp;|&nbsp; Email &nbsp;|&nbsp; Education &nbsp;|&nbsp; Teaching &nbsp;|&nbsp; Skills &nbsp;|&nbsp; Other funding &nbsp;|&nbsp; Other work &nbsp;|&nbsp; Videos &nbsp; ">CV, skills, funding, videos, etc.</span>'
  url = '#bio'
  weight = 40
  
[[main]]
   name = 'Blog'
   url = '#blog'
   weight = 50
