# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = 'Publications'
  url = '#publication'
  weight = 10

[[main]]
  name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; Web applications and data dashboards &nbsp; ">Web Apps</span>'
  url = '#applications-and-dashboards'
  weight = 20
  
[[main]]
  name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; Presentations and workshops &nbsp; ">Presentations</span>'
  url = '#workshops'
  weight = 30

[[main]]
  name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; Contact &nbsp; | &nbsp; CV &nbsp; | &nbsp; Work &nbsp; | &nbsp; Education &nbsp; | &nbsp; Teaching and supervision &nbsp; | &nbsp; Funding &nbsp; | &nbsp; Other work &nbsp; | &nbsp; Skills &nbsp; ">CV+</span>'
  url = '#bio'
  weight = 40
  
[[main]]
   name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; Videos and podcasts &nbsp; ">Multimedia</span>'
   url = '#multimedia'
   weight = 50
  
[[main]]
   name = '<span data-toggle="tooltip1" data-placement="bottom" title=" &nbsp; Short essays &nbsp; | &nbsp; Tutorials &nbsp; | &nbsp; Inquiries &nbsp; | &nbsp; Functions for the implementation of experiments, data analysis and other purposes &nbsp; ">Resources</span>'
   url = '#blog'
   weight = 60

[[main]]
   name = "<i class='fas fa-search js-search-trigger'></i> <span class='d-lg-none js-search-trigger'>Search</span>"
   url = '#'
   weight = 70
